version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
