name: Threat Mon Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Setup SSH key for authentication
        run: |
          mkdir -p ~/.ssh
          cp ./umer.pem ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VM to known_hosts
        run: |
          ssh-keyscan -H 13.60.83.34 >> ~/.ssh/known_hosts

      - name: Ensure Directory Permissions on VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.60.83.34 "sudo mkdir -p /home/py_bg_remover && sudo chown -R ubuntu:ubuntu /home/py_bg_remover && sudo chmod -R 755 /home/py_bg_remover"

      - name: Synchronize Code with VM Using rsync and SSH key
        run: |
          rsync -avz --exclude='.git' --exclude='.env' --exclude='data' \
            --no-perms --omit-dir-times --no-group \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ ubuntu@13.60.83.34:/home/py_bg_remover

      - name: Restart Docker Compose Services
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 13.60.83.34
          username: ubuntu@13.60.83.34
          key: ./umer.pem
          script: |
            echo "Stopping existing Docker Compose services..."
            cd /home/py_bg_remover
            sudo docker-compose down
            echo "Starting Docker Compose services..."
            echo "Enabling Docker BuildKit..."
            export DOCKER_BUILDKIT=1
            sudo docker-compose build
            sudo docker-compose up -d
            echo "Successfully deployed the application!"
